version: '3.8'
services:

  postgres:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: userpgdb_docker
      POSTGRES_PASSWORD: p4zWorD_d0k3r
      POSTGRES_DB: labdb
      TZ: 'America/Costa_Rica'
      PGTZ: 'America/Costa_Rica'
    ports:
      - '5432:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'postgres-data:/var/lib/postgresql/data/'
    networks:
      - lab-net
    restart: always
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@labcr.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Ad1_8RhlnKC}
      TZ: 'America/Costa_Rica'
    volumes:
      - './dbbackups:/var/lib/pgadmin/dbbackups'
      - 'pgadmin-data:/root/.pgadmin'
    ports:
      - '5454:80'
    networks:
      - lab-net
    restart: always
    depends_on:
      - postgres

  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres_container
      DB_PORT: 5432
      DB_DATABASE: labdb
      DB_SCHEMA: lab_keycloak
      DB_USER: userpgdb_docker
      DB_PASSWORD: p4zWorD_d0k3r
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: kc_T1sa0Kpf4
      TZ: 'America/Costa_Rica'
    ports:
      - '9091:8080'
    networks:
      - lab-net
    restart: always
    depends_on:
      - postgres
    volumes:
      - './themes:/opt/jboss/keycloak/themes' #Posteriormente esta carpeta se usará para cargar el tema
     
  ldap:
    image: osixia/openldap:latest
    container_name: ldap_container
    environment:
      - LDAP_ORGANISATION="MyCompany CR"
      - LDAP_DOMAIN=labcr.com
    ports:
      - "389:389"
      - "636:636"
    networks:
      - lab-net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin_container
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap
    networks:
      - lab-net
    restart: always

networks:
  lab-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
